name: Install-deps and Build

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:

  Install-build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2]

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install-deps
        run: yarn

      - name: Build
        run: npm run build

      - name: Push build files to release branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: release
          folder: docs
          single-commit: true
          clean: true
    
